spring:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/learning?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: net.sf.log4jdbc.DriverSpy